server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DharmalaRepo/society-config-repo
          default-label: main
          clone-on-start: true
          username: DharmalaRepo
          password: ${{secrets.GITHUB_TOKEN}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true